#!/bin/sh
# Erst wird ein neuws "repository" bei github.ccom hergestellt.
# Darin lediglich README.md, LICENSE
# Dies wird in ein lokales Verzeichnis 
# mit demselben Namen wie das "repository" geklont",
# also kopiert.
# Dort hhinein werden alle interessierenden Dateien kopiert und
# add
# commit
# push

git config --global credential.helper cache
git config --global credential.helper 'cache --timeout=36000'

pushd /data6/home/hanno/dynamische-adressen-ohne-make/
git clone https://github.com/gerdkolano/update-dns.git
mv * update-dns
cd update-dns/

git add .
git commit -m "first commit"
git push -u origin master 

# Arbeite am Verzeichnis

git add git-how-to 
git commit -m second
git push -u origin master

# Arbeite am Verzeichnis

git add git-how-to 
git commit -m second
git push -u origin master


exit 0

